### ISSUE TITLE
Write content for Connect

### ISSUE THREAD

**Issue by admbtlr** [eHealthAfrica/documentation#16]

**Comment by admbtlr** [comment]
@lucychambers Could you take care of this?

**Comment by lucychambers** [comment]
@adamvert probably not in the next couple of weeks. We could also ask @panys (who isn't appearing in the list of people who can see this.

**Comment by admbtlr** [comment]
Sorry @lucychambers, I was importing all the issues from the old documentation site, and Github thought they were being newly created - that question for you was actually asked by Francesco back in June :)

**Comment by lucychambers** [comment]
Ah ok :D

On 27 January 2016 at 11:13, adamvert notifications@github.com wrote:

> Sorry @lucychambers https://github.com/lucychambers, I was importing
> all the issues from the old documentation site, and Github thought they
> were being newly created - that question for you was actually asked by
> Francesco back in June :)
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/eHealthAfrica/documentation/issues/16#issuecomment-175527305
> .

## 

Lucy Chambers
Product Owner
eHealth Africa
+49 178 1427234
