### ISSUE TITLE
What is the recommended way to register the name of a person?

### ISSUE THREAD

**Issue by admbtlr** [eHealthAfrica/documentation#17]
Considering for example input fields on a form, should they be:

1- `name`
2- `name`, `surname`
3- `name`, `other names`
4.- ... ?

**Comment by admbtlr** [comment]
4 - first name, last name (NutSurv)
5 - name, surname, prename (HAT)

**Comment by admbtlr** [comment]
@cristinasantamarina hum, these are different alternatives. The point is not how we are inconsistently doing this now, but what is the recommended way of doing this in the future. For example, using just a single `name` field in the future could save us many problems, supporting easily cultures with arbitrarily complex naming conventions

**Comment by admbtlr** [comment]
oh you just wanted to extend the collection ... allright sorry :)

**Comment by admbtlr** [comment]
@danse Yes just pointing out which other alternatives we use. I think if we want to set an standard it is worth looking at what we have. 

Is the idea to replace the current models or to aim at using a standard from now on?

**Comment by admbtlr** [comment]
Just a recommendation for the future, answering to questions like the recent one from @lucychambers 

> What is conventional wisdom on how to do name fields? One field for ‘name’ or two ‘First name / Last name’

**Comment by danse** [comment]
Hum this is a weird issue, it looks like it is missing some comments. I know that you labeled it as _ignore_, but then what is the use of adding it?

**Comment by admbtlr** [comment]
I tried to import all the issues from the old documentation site to the new one. It worked, but all the issues & comments are from me, and all the dates are the moment I imported them. Apparently, this is unavoidable. 

So now I've just left all the issues in the old repo, tagged as 'documentation site' - eg. https://github.com/eHealthAfrica/eHealthAfrica.github.io/issues/28
